'use strict';
module.exports = [
  {
    visible: true,
    fileName: 'is-ie-a-business-in-2020',
    title: 'Is Internet Explorer a business in 2020?',
    conclusion: 'Internet Explorer has a very low quantity users and it is not a good business to support this browser. If your app is IE capable, probably you are moving the money resources generated by Chrome to compensate the revenue that is not generated by IE. It sounds a good idea for sales/marketing reasons in a big company where resources are infinite, but not represent the reality of most companies and startup.',
    tags: ['ie', 'internet-explorer', 'business', 'ROI', 'timeboxing', 'time-management', 'negotiation', 'product-manager', 'What about'],
    author: 'pieroblunda',
    revisionDate: new Date('2020-05-04'),
    relatedArticles: [
      {
        text: 'Platform market share',
        link: 'https://gs.statcounter.com/platform-market-share/desktop-mobile-tablet'
      },{
        text: 'A business case for dropping internet explorer',
        link: 'https://css-tricks.com/a-business-case-for-dropping-internet-explorer/'
      },{
        text: 'Timeboxing - Wikipedia',
        link: 'https://en.wikipedia.org/wiki/Timeboxing'
      },{
        text: 'What is ROI',
        link: 'https://www.workana.com/i/glossary/what-is-roi/'
      },{
        text: 'Diminishing returns',
        link: 'https://en.wikipedia.org/wiki/Diminishing_returns'
    ],
    continueReading: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ]
  },{
    visible: true,
    fileName: 'how-to-manage-a-technical-debt',
    title: 'How to manage a technical debt',
    conclusion: 'Do not forget why you are in the project. Everyone has a goal as team member in their single role, but... do you remember exactly what is the project goal? Focus in your goal. Speak with your scrum master in order to be aligned. Classify technical debt as quality issues (yes! there are bugs too!). Use timeboxing to control time spent and use time to improve KPI\'s. Did you define KPI\'s? You should.',
    tags: ['technical debt', 'todo', 'timeboxing', 'sprint', 'quality'],
    author: 'pieroblunda',
    revisionDate: new Date('2020-07-20'),
    relatedArticles: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ],
    continueReading: [
      {
        text: 'Timeboxing - Agile alliance',
        link: 'https://www.agilealliance.org/glossary/timebox'
      },{
        text: 'Krzysztof Liszewski - Agile blog',
        link: 'https://4agile.pl/how-to-manage-technical-debt/'
      },{
        text: 'UML & Patters',
        link: 'https://www.amazon.it/Applying-UML-Patterns-Introduction-Object-Oriented/dp/0582832489/ref=sr_1_1?dchild=1&qid=1594364693&refinements=p_27%3ACraig+Larman%2Cp_n_feature_browse-bin%3A509817031&rnid=509815031&s=books&sr=1-1'
      },{
        text: 'Technical debt - Wikipedia',
        link: 'https://en.wikipedia.org/wiki/Technical_debt'
      }
    ]
  },{
    visible: false,
    fileName: 'the-40-min-rule',
    title: 'The 40 minutes rule',
    conclusion: 'Considerer roll back changes if you detect unstable a stable branch.',
    tags: [],
    author: 'pieroblunda',
    revisionDate: new Date('2019-11-11'),
    relatedArticles: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ],
    continueReading: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ]
  },{
    visible: false,
    fileName: 'choosing-a-correct-branching-model',
    title: 'Choosing a correct branching model',
    conclusion: 'Do not rush to choose GitFlow. You should use the GitLab flow 99.9% of the time',
    tags: [],
    author: 'pieroblunda',
    revisionDate: new Date('2019-11-11'),
    relatedArticles: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ],
    continueReading: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ]
  },{
    visible: false,
    fileName: 'what-about-estimations',
    title: 'What about estimations',
    conclusion: 'Estimate approximate time is not absolutely necessary. Involve the team when to estimate only when customer needs a budget. Doubt if you are estimating each task. Negotiate a solution with the customer is maybe the best choice. Be user-focused and set good sprint goals.',
    author: 'pieroblunda',
    revisionDate: new Date('2019-12-18'),
    tags: [
      'timing',
      'agile',
      'sprint-planning',
      'sprint-goal'    ],
    relatedArticles: [
      {
        text:  'Wikipedia - Time management',
        link: 'https://en.wikipedia.org/wiki/Time_management'
      },{
        text: 'Software development effort estimation',
        link: 'https://en.wikipedia.org/wiki/Software_development_effort_estimation'
      },{
        text: 'Creating good sprint goals',
        link: 'https://www.agilesocks.com/creating-good-sprint-goals/'
      },{
        text: 'Official Scrum guide',
        link: 'https://www.scrumguides.org/docs/scrumguide/v2017/2017-Scrum-Guide-US.pdf'
      },{
        text: 'Wikipedia - The Agile Manifesto',
        link: 'https://en.wikipedia.org/wiki/Agile_software_development#The_Agile_Manifesto'
      },{
        text: 'Wikipedia - Velocity',
        link: 'https://en.wikipedia.org/wiki/Velocity_(software_development)'
      },{
        text: 'Rewarding agile ceremonies',
        link: 'https://www.mendix.com/blog/rewarding-agile-ceremonies/'
      }
    ],
    continueReading: [
      {
        text: 'what-about-task-splitting',
        link: 'what-about-task-splitting'
      },{
        text: 'why-split-manteinability-issues',
        link: 'why-split-manteinability-issues'
      }
    ],
    revisionDate: '2019-12-18T08:01:16.764Z'
  },{
    visible: false,
    fileName: 'what-about-task-splitting',
    title: 'What about task splitting',
    conclusion: 'Split your task in a vertical way. Your product owner and others stakeholder love it. Do not run for optimizing your code and avoid to do manteinance task that are not necessary. Focus in the business and show to the customer exactly he want to see.',
    author: 'pieroblunda',
    tags: [
      'sprint-planning',
      'product-owner',
      'task-management',
      'vertical-splitting',
      'project-management',
      'agile',
      'scrum'
    ],
    relatedArticles: [
      {
        text: 'Wikipedia - Vertical slice',
        link: 'https://en.wikipedia.org/wiki/Vertical_slice'
      },{
        text: 'Patterns for splitting user stories',
        link: 'https://agileforall.com/patterns-for-splitting-user-stories/'
      },{
        text: 'Vertical slices and scale',
        link: 'https://agileforall.com/vertical-slices-and-scale/'
      },{
        text: 'Linkeding - Vertical agile approach work break down team donald ewart',
        link: 'https://www.linkedin.com/pulse/vertical-agile-approach-work-break-down-team-donald-ewart'
      },{
        text: 'Splitting stories into small vertical slices',
        link: 'https://blogs.adobe.com/agile/2013/09/27/splitting-stories-into-small-vertical-slices/'
      }
    ],
    continueReading: [
      {
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      },{
        text: '',
        link: ''
      }
    ],
    revisionDate: '2020-01-07T12:59:33.390Z'
  }//- @NewArticleHere
];
